services:
  db:
    image: postgres:16-alpine
    container_name: store_db
    environment:
      POSTGRES_USER: asdf
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: db_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d nagi_store"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
